### ISSUE TITLE
VoodooI2C Interrupts vs. Polling

### ISSUE THREAD

**Issue by whatnameisit** [tctien342/Asus-Vivobook-S510UA-Hackintosh#25]
Hi. I use X510UA-BQ490, and I've had problems with the touchpad where in the interrupts mode(which is the one provided in the commit) any gesture gets broken more and more as the CPU usage increases. I've switched to the polling mode with some helps from Ben at the VoodooI2C gitter chatroom, it works great.
[Polling.zip](https://github.com/tctien342/Asus-Vivobook-S510UA-High-Sierra-10.13-Hackintosh/files/3169826/Polling.zip)
Switch from the original ELAN SSDT to the one I uploaded, and add the Clover rename in the config.plist

**Comment by whatnameisit** [comment]
If anyone got a better method in the interrupts mode, please share.

**Comment by LeeBinder** [comment]
great, thanks @whatnameisit , will try in a few days (am too busy with a project so do not have space for testing right now, but am sure curious).

**Comment by LeeBinder** [comment]
@whatnameisit : do you know how to see if polling mode is really active? Some specific place in IOReg Explorer?

And which VoodooI2C kexts do you use: the one from this current release here, or latest 2.1.6 stock from alexandred, or the most current ones from hieplviep, or ..?

Oh, and does your X510UA-BQ490 have ELAN1300 or 1200?

**Comment by whatnameisit** [comment]
@LeeBinder , I have ELAN1200. Its device name is ETPD in IOReg, and I'm currently using alexandred's latest kexts. The ones provided by this tctien342's git seem to have problems in 10.14.4 (and likely 10.14.5...) which is why they updated the kexts to 2.1.6, I think.
I am on 10.14.4 right now, will be updating to 10.14.5 and I hope nothing breaks...

**Comment by LeeBinder** [comment]
I see. Note that tctien342's ELAN SSDT might be optimized for ELAN1300 which is what he (and I also) have in our Vivobooks, so your polling SSDT might not be fully compatible. What do you think? Or would we need to ask Ben?

Good luck updating to 10.14.5 👍

**Comment by whatnameisit** [comment]
@LeeBinder Ben told me it's more like any device older than KBL-R should have USTP equal to one to in order to enable SSCN and FMCN methods for smoother gestures. So I was not sure if setting USTP equal to one would fix my issues, but it did! He didn't specify if the patch was for ELAN1200 only, so it might go well with ELAN1300. It's up to you to try :)

**Comment by whatnameisit** [comment]
Polling works OK in 10.14.5.
Interrupts does not work (I haven't tested it myself, but I had a report from someone with the same model as mine. 별초롱이 at x86.co.kr).

**Comment by LeeBinder** [comment]
Great information. I'll keep observing my VoodooI2C 2.0.3's performance (no glitches anymore ever since the change to polling, it seems). In case pointer movements get out of hands again, I'd contact Ben if there might need to be custom adaptations for the v.2.0.3 because I do not know if the SSDT and config.plist ACPI patch also fully applies to the legacy 2.0.3 or ONLY to the MT2 based 2.1.x VoodooI2c . Thanks again @whatnameisit !!

**Comment by LeeBinder** [comment]
Still perfect. Movements went berserk again just once ever since and settled back in immediately after hitting some function key (Fn11 in that case to be specific). Also the ACPI patch in Clover is obviously working for the legacy v.2.0.3, too, because when I disable it -> no trackpad.

Thanks again, buddy - you perfectionized my Vivohack experience 💯 

@whatnameisit do you want to share this in [[Guide][New VoodooI2C] Asus Vivobook S15 X510UAR 10.13+](https://www.tonymacx86.com/threads/guide-new-voodooi2c-asus-vivobook-s15-x510uar-10-13.245445/), too?

**Comment by whatnameisit** [comment]
@LeeBinder If it works, good for you :)
Sharing it at tonymacx86: Done!

**Comment by LeeBinder** [comment]
@whatnameisit tctien342 provides two entries in his clover.plist for our ELAN 1300:
<details>
  <summary>click to expand</summary> 

```
<dict>
     <key>Comment</key>
     <string>ELAN: change Method(_STA,0,NS) in GPI0 to XSTA</string>
     <key>Disabled</key>
     <true/>
     <key>Find</key>
     <data>X1NUQQCgCZNTQlJH</data>
     <key>Replace</key>
     <data>WFNUQQCgCZNTQlJH</data>
</dict>
<dict>
     <key>Comment</key>
     <string>ELAN: change Method(_CRS,0,S) in ETPD to XCRS</string>
     <key>Disabled</key>
     <true/>
     <key>Find</key>
     <data>X0NSUwgIU0JGSQ==</data>
     <key>Replace</key>
     <data>WENSUwgIU0JGSQ==</data>
</dict>
```
</details>

For the polling patch you uploaded above
<details>
  <summary>click to expand</summary> 

```
<dict>
     <key>Comment</key>
     <string>ELAN: change USTP to XSTP to assign default values to SSCN and FMCN</string>
     <key>Disabled</key>
     <false/>
     <key>Find</key>
     <data>
     VVNUUA==					</data>
     <key>Replace</key>
     <data>
     WFNUUA==					</data>
</dict>
```
</details>
to work with your SSDT-ELAN-POLLING.aml
<details>
  <summary>click to expand</summary> 

```
DefinitionBlock ("", "SSDT", 2, "hack", "elan", 0x00000000)
{
    External (_SB_.PCI0.GPI0, DeviceObj)
    External (_SB_.PCI0.I2C1.ETPD, DeviceObj)

    Method (_SB.PCI0.GPI0._STA, 0, NotSerialized)  // _STA: Status
    {
        Return (0x0F)
    }

    Scope (_SB.PCI0.I2C1.ETPD)
    {
        Method (_CRS, 0, Serialized)  // _CRS: Current Resource Settings
        {
            Name (SBFB, ResourceTemplate ()
            {
                I2cSerialBusV2 (0x0015, ControllerInitiated, 0x00061A80,
                    AddressingMode7Bit, "\\_SB.PCI0.I2C1",
                    0x00, ResourceConsumer, , Exclusive,
                    )
            })
            Return (SBFB) /* \_SB_.PCI0.I2C1.ETPD._CRS.SBFB */
        }
    }
    Name (USTP, One)
}
```
</details>

I had always just disabled tctien342's GPIO patch.

Now I was wondering if I should also disable his ETPD patch to hopefully get a smoother touchpad experience, so I checked your [X510UA-BQ490 repo](https://github.com/whatnameisit/Asus-Vivobook-X510UA-BQ490-Mojave-10.14.6-Hackintosh) and was happy to see that you updated it just yesterday.

But after looking through it more closely I am now confused, because I don't see any of your above ELAN I2C patch names or strings (ELAN/ I2C/ SSCN/ XSTP/ USTP/ FMCN) present in [your config.plist](https://github.com/whatnameisit/Asus-Vivobook-X510UA-BQ490-Mojave-10.14.6-Hackintosh/blob/master/Clover%20EFI/EFI/CLOVER/config.plist), and your [SSDT-I2C1_USTP.dsl](https://github.com/whatnameisit/Asus-Vivobook-X510UA-BQ490-Mojave-10.14.6-Hackintosh/blob/master/Clover%20EFI/EFI/CLOVER/ACPI/patched/SSDT-I2C1_USTP.dsl) looks (compared to above SSDT-ELAN-POLLING.dsl) quite different, too :
<details>
  <summary>click to expand</summary> 

```
DefinitionBlock ("", "SSDT", 2, "hack", "elan", 0x00000000)
{
#endif
    External (_SB_.PCI0.I2C1, DeviceObj)    // (from opcode)

    Scope (_SB.PCI0.I2C1)
    {
        If (_OSI ("Darwin"))
        {
            Name (USTP, One) // "Infinite click" fix.
            Name (SSCN, Package (0x03) // Assignment of SSCN and FMCN
            {
                0x0210, 
                0x0280, 
                0x1E
            })
            Name (FMCN, Package (0x03)
            {
                0x80, 
                0xA0, 
                0x1E
            })
        }
    }
#ifndef NO_DEFINITIONBLOCK
}
```
</details>

so now I am wondering if I can adapt any of your new commits for my ELAN 1300, with the goal of having a smoother experience.

Can you shine a light on what you suggest?

Thanks for your efforts & greetings to Korea

PS: no idea why there's an empty line before some of the spoilers.. the text does not reflect that...

**Comment by LeeBinder** [comment]
I just replaced your old ELAN-POLLING.aml with your new SSDT-I2C1_USTP.aml, deactivated ALL I2C/ ELAN specific patches in Clover config.plist, rebooted -> touchpad still working with latest VoodooI2C v.2.3. So that's optimal for now? No advantage in having additional patches activated?

However still experiencing the horrible [dragging/ selecting etc. bug](https://github.com/alexandred/VoodooI2C/issues/208) due to individual TP buttons :( Are you, too, by any chance?

[EDIT]: for the sake of experimenting, I next also removed your new SSDT-I2C1_USTP.aml from ACPI/patched, rebooted, and TP still working!! Hum? Seems like a new feature in VoodooI2C v.2.3? But am I in polling or in GPIO interrupts mode now?

**Comment by whatnameisit** [comment]
@LeeBinder 
Integer USTP=1 is all that's required for my trackpad to function with VoodooI2C package in macOS.
In many Vivobook's DSDT, a FieldUnitObject USTP already exists in the root scope (which could be understood as "not inside any scope, or directory"), so in order to inject an integer USTP in the root scope and meet ACPI Specs requirements (same named objects cannot exist in the same scope), config.plist's USTP to XSTP is necessary. 
Originally I thought, with the config.plists USTP to XSTP and _CRS to XCRS, SSDT-ELAN-POLLING.aml was needed as it defined USTP=1 in the root scope and also renamed SBFI to SBFB inside _CRS. But SBFB (and SBFG deleted from the ELAN SSDT provided by tctien342) is only required for Interrupts mode. If SBFB and SBFG are not returned by _CRS, Interrupts mode is not activated and the VoodooI2CHID switches to the Polling mode, regardless of whether it is SBFB or SBFI that is returned by _CRS. At this point, you can see no DSDT edits are needed for my touchpad to function in Polling mode. One thing's left: for smooth transition (with my trackpad) Integer USTP=1 needs to be defined in the ACPI, but I found out it does not have to be in the root scope. So I left the FieldUnitObject USTP as is and inserted the integer USTP=1 in the \_SB.PCI0.I2C1 scope (Now I think that could be expected because Ben said in many systems USTP=1 is needed for SSCN and FMCN to be used in many laptops' DSDTs by the way the code is written, and S&F are required for macOS touchpad with SKL or older systems. But I don't think our Vivobooks' DSDTs mention S&F at all, and our system is KBL (or KBL-R). So SSCN and FMCN are not really necessary (but if they don't exist, an error message is given saying that they are not found and then default values are assigned and I didn't like the error lol).
So no config.plist renames are needed for my touchpad, but SSDT-I2C1-USTP.aml is needed.
About the multiple trackpad buttons issues, my trackpad is one pad, no extra buttons. So I don't have any problems dragging and selecting. I forgot if right click in the right part of the touchpad with one finger worked or not. I will test it when I get home.
Hope this helps :)

**Comment by whatnameisit** [comment]
The SSDT is definitely needed (at the moment) for my trackpad to work smoothly. If I don't have it, any touch input may fail with high CPU usage. But your trackpad may be different because you still have trouble dragging and selecting, right?

**Comment by LeeBinder** [comment]
Thank you @whatnameisit for your comprehensive explanation. You obviously are very knowledgeable!

I'll keep observing how the TP performs with SSDT-I2C1-USTP.aml vs. ELAN-POLLING.aml. So far it feels smooth.

Yes, I'm still have trouble dragging and selecting. It's however been tangibly better with your polling approach, vs. GPIO ACPI patches + SSDT.

So obviously my ELAN 1300 IS different than your ELAN 1200. Mine also has a smooth one-piece surface, but underneath I'm certain there are TWO buttons, left AND right; because in Windows, Linux and with VoodooI2C v.2.0.3 in High Sierra, I can put a piece of paper over the TP and still click & drag successfully. That does NOT work anymore with VoodooI2C ever since 2.1.

I attached ACPI/original + IOReg in case you feel like looking if SSDT-I2C1-USTP might need to be adapted in any way for this ELAN 1300. Only if it's little effort for you.

[ACPI + IOReg.zip](https://github.com/tctien342/Asus-Vivobook-S510UA-High-Sierra-10.13-Hackintosh/files/3979893/ACPI.%2B.IOReg.zip)

**Comment by LeeBinder** [comment]
This repo has found a new home at the current maintainer's GitHub corner:

https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh/

If still interested, please download the latest release from over there, **read the _ReadMe_ completely at least once**, and follow all instructions all the way to the end.

In case an issue arises, please post it via the issues section over there.

This issue will now be closed.
