### ISSUE TITLE
Dual Boot (Win + MacOS) on Vivobook S510 BQ414T

### ISSUE THREAD

**Issue by solirjin** [tctien342/Asus-Vivobook-S510UA-Hackintosh#50]
I have the same specification laptop as the topic and 2 storage drives (SSD + HDD). I did install hackintosh on the laptop on SSD, could i continue installing window on HDD? If not, can you show me how the boot 2 OS in 2 different storage, or 1 storage(SSD)?

**Comment by LeeBinder** [comment]
My Vivo also has SSD + HDD. I have my main Windows and also High Sierra, Mojave and Catalina on SSD (the 3 macOS flavors in one space-saving APFS container - lovin' it), and a test Windows on HDD (along with an ExFat Data partition shared r/w by Win & Mac). On HDD Windows is too slow to work with. I have EFI ONLY for Clover, and a 2nd EFI partition somewhere else on the SSD ONLY for Windows. I simply cloned it from EFI with the trial version of Paragon Hard Disk Manager (both ports work for that, the [one for Windows](https://www.paragon-software.com/home/hdm-windows/#) and [the one for Mac](https://www.paragon-software.com/hdm-mac/#), but you certainly can take any other partition tool for cloning ¹), renamed it to MS-EFI, then removed the Microsoft stuff from EFI.

Entry in Clover config GUI:
![MS-EFI](https://user-images.githubusercontent.com/39203497/75123803-0ca8b200-56ab-11ea-8bbf-0d890ec7d096.jpg)

Ever since, when I update Windows, it does NOT mess with my EFI partition anymore (which it did before when I was still sharing EFI for both, Clover and MS)!!!

-------------------
¹ my favs for Windows (the trial or free versions suffice): [R-Drive Image](https://www.drive-image.com/Drive_Image_Download.shtml) (if the trial period has expired, simply uninstall, reinstall); [Eassos DiskGenius](https://www.diskgenius.com/partition-management.php) (ex. PartitionGuru); [MiniTool Partition Wizard](https://www.partitionwizard.com/download.html)

**Comment by LeeBinder** [comment]
@solirjin I updated my reply above with links for convenience

**Comment by LeeBinder** [comment]
### Resize an APFS Container:

1) make space BEHIND the APFS container to be resized

2) adapt diskXsY to match the APFS container to be resized, e.g. disk0s9:

diskutil apfs resizeContainer diskXsY 0

examples:
diskutil apfs resizeContainer disk0s7 0
diskutil apfs resizeContainer disk1s7 0

If you can only make space before:

A) do so with Paragon Hard Disk Manager for Mac or Windows

B) now boot Windows or Paragon Hard Disk Manager 17.x (or higher) Advanced PE-based Recovery Media

C1) run Paragon Hard Disk Manager 17.x (or higher) Advanced for Windows, highlight the APFS container to be resized and drag the slider under "Unallocated space before" all the way to the left. That should display the free space now under "Unallocated space after"

C2) click onto "Change now". That will MOVE the APFS container to be resized, creating the free space above.

D) continue with 2) above

**DETAILS:**

To anyone running into the “the target disk is too small” issue, here’s what I believe is happening:

APFS is only able to resize itself to space on the disk that exists beyond/ above the last sector of the existing APFS container. If you have deleted a partition that was placed before the beginning of the APFS container, it won’t be accessible to resizing your existing APFS container. In such an instance, my recommendation is either use Paragon Hard Disk Manager 17.x (or higher) Advanced for Windows (needless to say you need Windows installed for that), or (if you only have macOS installed), to make a clone of your APFS drive, using either Carbon Copy Cloner or Super Duper, and then repartitioning the entire drive the way you want…

**Comment by solirjin** [comment]
> ### Resize an APFS Container:
> 1. make space BEHIND the APFS container to be resized
> 2. adapt diskXsY to match the APFS container to be resized, e.g. disk0s9:
> 
> diskutil apfs resizeContainer diskXsY 0
> 
> examples:
> diskutil apfs resizeContainer disk0s7 0
> diskutil apfs resizeContainer disk1s7 0
> 
> If you can only make space before:
> 
> A) do so with Paragon Hard Disk Manager for Mac or Windows
> 
> B) now boot Windows or Paragon Hard Disk Manager 17.x (or higher) Advanced PE-based Recovery Media
> 
> C1) run Paragon Hard Disk Manager 17.x (or higher) Advanced for Windows, highlight the APFS container to be resized and drag the slider under "Unallocated space before" all the way to the left. That should display the free space now under "Unallocated space after"
> 
> C2) click onto "Change now". That will MOVE the APFS container to be resized, creating the free space above.
> 
> D) continue with 2) above
> 
> **DETAILS:**
> 
> To anyone running into the “the target disk is too small” issue, here’s what I believe is happening:
> 
> APFS is only able to resize itself to space on the disk that exists beyond/ above the last sector of the existing APFS container. If you have deleted a partition that was placed before the beginning of the APFS container, it won’t be accessible to resizing your existing APFS container. In such an instance, my recommendation is either use Paragon Hard Disk Manager 17.x (or higher) Advanced for Windows (needless to say you need Windows installed for that), or (if you only have macOS installed), to make a clone of your APFS drive, using either Carbon Copy Cloner or Super Duper, and then repartitioning the entire drive the way you want…

Thank you very much, it's pretty helpful. But I'm newbie and have a little knowledge of hackintosh, I just only know how setup MacOS solely on my laptop. Can you show me or give me a guideline for dual booting MacOS and Win on SSD?. Thank youu~~~

**Comment by LeeBinder** [comment]
c'mon @solirjin - if you managed to hackintosh a Laptop, you'll sure be able to move a few sliders + do some clicks or drag & drop in a partitioning app, plug in a USB flash drive with Windows 10, and install it to the free partition you created in the step before .. - latter is of a much less difficulty level than the first (h'tosh) ;)

I can't take you by the hand but am encouraging and empowering you.

**Comment by LeeBinder** [comment]
This repo has found a new home at the current maintainer's GitHub corner:

https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh/

If still interested, please download the latest release from over there, **read the _ReadMe_ completely at least once**, and follow all instructions all the way to the end.

In case an issue arises, please post it via the issues section over there.

This issue will now be closed.
