### ISSUE TITLE
My VivoBook's Touchpad is not detected/usable after the 10.15.3 update

### ISSUE THREAD

**Issue by HunterAhlquist** [tctien342/Asus-Vivobook-S510UA-Hackintosh#51]
It worked just fine prior, but now on this update it does not function or even gets detected whatsoever.

**Comment by whatnameisit** [comment]
rebuild kextcache

**Comment by LeeBinder** [comment]
@HunterAhlquist two things:

1. why do you write "will"? The 10.15.3 final update has been around for 23 days (Jan. 28).

2. Touchpad working fine here in 10.15.3. As whatnameisit wrote, please rebuild the kextcache. That's often needed after an OS update (I think because these kexts aren't signed).

I adapted the issue title accordingly. Please kindly report back :+1:

**Comment by HunterAhlquist** [comment]
I dont know how I made such a rookie move, I should have known better than to not rebuild my kext cache. Sorry guys! 
Also "will" was a typo.

**Comment by LeeBinder** [comment]
LOL no worries - just transfer $1,000 to a charity of your choice and you're all set .. ;)

I've been wrapping my head around this issue for quite a while, wondering why especially the touchpad kext(s?) tend to get disabled after an update but other also non-signed kexts don't.
