### ISSUE TITLE
Big Sur please READ!!!

### ISSUE THREAD

**Issue by ngocanhnckh** [tctien342/Asus-Vivobook-S510UA-Hackintosh#56]

**Comment by LeeBinder** [comment]
After reading the comments below, ngocanhnckh removed his request for Big Sur compatibility, which is positively sane.

I don't have neither capacity nor mind to deal with Big Brother now and for the near future. For those who do opt to install Apple's spy OS, certainly **_not_** as main production OS but only for reasons of experimentation and curiosity, please do read all below, then do as master **whatnameisit** writes [here](https://github.com/tctien342/Asus-Vivobook-S510UA-Hackintosh/pull/66#issuecomment-735231259):

> The Clover in this original branch and mine does not support Big Sur. Just update Clover and switch from AptioMemoryFix to **OpenRuntime** and **OCQuirks** and you'll be fine for now.

In addition, simply also update all kexts to their most recent versions. If you encounter an issue with a kext, simply downgrade that one until you're satisfied.

Also I am sticking to Clover for now as my main bother simply because I also don't feel like dealing with OpenCore right now even though I am very well aware of its advantages over Clover. But below you'll find some gold nuggets which should make you a happy OpenCore + Big Brother camper, if you decide to venture ahead on that route :)

**Comment by LeeBinder** [comment]
@ngocanhnckh try attached file, credits to jhsvip for [his share here](https://github.com/CloverHackyColor/CloverBootloader/issues/200#issuecomment-661855232).

Also [his other share](https://github.com/CloverHackyColor/CloverBootloader/issues/200#issuecomment-661180687) might be helpful, too (or might not because he very most likely does not use a VivoBook). Note that I cannot test any of this because I will not install Big Sur until the final.

[cure Big Sur black screen.zip](https://github.com/tctien342/Asus-Vivobook-S510UA-Hackintosh/files/4956920/cure.Big.Sur.black.screen.zip)

**Comment by LeeBinder** [comment]
lvs1974 just updated his [CpuTscSync kext](https://github.com/lvs1974/CpuTscSync/releases/) for Big Sur Beta compatibility. It is necessary for booting macOS with current VivoBook BIOS versions and more compatible than VoodooTSCSync.kext even for Catalina and Mojave, solving occasional TSC related kernel panics on wake-up. You are invited to test it in your Big Sur Beta install and report back.

Make sure you have removed any VoodooTSCSync.kext (from /L/E and from EFI/Clover/kexts/Other and any 10.x sub folder) because you may only have ONE TSC sync kext active!

**Comment by tctien342** [comment]
@ngocanhnckh please test this, currently built for A510UF 8550U base on this repo, should work fine with big sur
[Vivobook-8550U-OC0.6.zip](https://github.com/tctien342/Asus-Vivobook-S510UA-Hackintosh/files/5057259/Vivobook-8550U-OC0.6.zip)

**Comment by LeeBinder** [comment]
oh, the great grandmaster himself is back in town - good going, Saintno 👍 

Are you still maintaining/ servicing your brother's VivoBook?

**Comment by LeeBinder** [comment]
I see a few questionable kexts in that OpenCore based release:
- HibernationFixup.kext : does deep sleep suddenly work with OC in Big Sur?
- SMCDellSensors.kext : a kext made for Dell works on Asus?

**Comment by tctien342** [comment]
> I see a few questionable kexts in that OpenCore based release:
> - HibernationFixup.kext : does deep sleep suddenly work with OC in Big Sur?
> - SMCDellSensors.kext : a kext made for Dell works on Asus?

- SMCDell not injected from opencore as not add to config, i just forgot to remove that @@

- HibernationFixup.kext still testing as my dell is working with it on big sur :3

**Comment by johnwtt** [comment]
currently stuck on the less than a minute

**Comment by LeeBinder** [comment]
@johnwtt still? I've experienced this sometimes with macOS hackintosh installs. Usually after a few forced power-offs and reboots back into the installer routine, it would finish installing eventually and boot into the desktop.

Fresh install or upgrade? If one method gets stuck, try the other method.

Also what would solve this for me sometimes is, however using Clover not OC: during Clover GUI, press the O key (for Clover options), hit the ENTER/ RETURN key, press the END key, add `-x` at the end of the line, hit ENTER/ RETURN again, END to the bottom of the menu, ENTER/ RETURN key to get back into the main Clover GUI boot menu, and boot back into the installer.

I do not know what the OC equivalent of adding `-x` as additional boot argument is.

**Comment by LeeBinder** [comment]
From [EFI Folders for All Chipsets (Clover and OpenCore) - Guides and Tutorials - Olarila](https://www.olarila.com/topic/5676-folders-for-all-chipsets-clover-and-opencore), you could try

[ Clover: NOTEBOOKS CHIPSET SERIES SKYLAKE+](https://tinyurl.com/vpecysf) (SKYLAKE / KABYLAKE / COFFEELAKE / WHISKEYLAKE / COMETLAKE)

or

OC: [NOTEBOOKS CHIPSET SERIES SKYLAKE+](https://tinyurl.com/swgnojg) (SKYLAKE / KABYLAKE / COFFEELAKE / WHISKEYLAKE / COMETLAKE)

**Comment by johnwtt** [comment]
just got big sur beta 1 install. Sleep doesn't work. Using tctien oc build

**Comment by LeeBinder** [comment]
hum - why the very old beta 1? They're already at [beta 5](https://drive.google.com/file/d/1Yrij1r31akTmw4lz4coiWBkhqSn4JC2_/view).. 

You might (should) also be able to update from within the install via Software Update.

Happy upgrading .. ;)

**Comment by johnwtt** [comment]
Just try all the way up to b5
I'm using the old method by applelife.ru team

**Comment by LeeBinder** [comment]
What you write is not fully clear.. did you succeed installing and booting all the way into beta 5, or are you going to try? It would be interesting to know if sleep and wake-up work fine in beta 5 with all latest kexts and either OC or Clover.

Also, could you please share the link to the method on applelife.ru which worked for you - maybe [this one](https://translate.googleusercontent.com/translate_c?depth=1&hl=en&pto=aue&rurl=translate.google.com&sl=ru&sp=nmt4&tl=en&u=https://www.applelife.ru/threads/ustanovka-macos-big-sur-11-0-beta-na-intel-pc.2945052/&usg=ALkJrhiXF-ZKZN0T7s-jonVZ2fdpP7vvIQ)?

**Comment by johnwtt** [comment]
yes, that is the method i use. so i just find the beta 5 image. i'm installing it

**Comment by LeeBinder** [comment]
`curl -O https://raw.githubusercontent.com/munki/macadmin-scripts/main/installinstallmacos.py && sudo /usr/bin/python installinstallmacos.py --raw --seedprogram DeveloperSeed`

**Comment by LeeBinder** [comment]
I'm very direct here now: whoever updates to Big Sur (at least at this stage but maybe in general) would out themselves as an utter fool & idiot. Why?

**Chilling articles about Apple privacy concerns:**

https://sneak.berlin/20201112/your-computer-isnt-yours/

https://9to5mac.com/2020/11/13/apple-server-outage-reveals-mac-privacy-concerns/

In German: [Big Sur hebelt Firewalls aus, um Daten an Apple zu senden – t3n – digital pioneers](https://t3n.de/news/macos-big-sur-apple-datenschutz-vpn-netzwerkfilter-1337470)

Comprehensive list of sites Apple access: https://support.apple.com/en-us/HT210060

cc @whatnameisit @tctien342 @hieplpvip

**Comment by ngocanhnckh** [comment]
Ok thanks I changed my mind

**Comment by LeeBinder** [comment]
Good. Honestly, they should've labeled it as what is is: Big BROTHER...

It's not smart anymore (well actually never was) to always mindlessly devour all the new shiny shtuff companies throw at us. Like the native indigenous people that fell for glimmering glass marbles. Not all that sparkles is gold; and the latest "bells-and-whistles" might just be bait to trick us. In the case of Big BROTHER Sur that orwellian 1984 has certainly become digital reality.

I'm sure hackers will figure out a way to nullify Big B. calling home big time. Until then: NO !!

**Comment by LeeBinder** [comment]
Anybody who's interested in installing Big Sur, please read https://github.com/tctien342/Asus-Vivobook-S510UA-Hackintosh/pull/66#issuecomment-735231259
